--- #YAML:1.0
name:                CGI-UploadEasy
version:             1.00
abstract:            Facilitate file uploads
license:             ~
author:              
    - Gunnar Hjalmarsson <cpan@gunnar.cc>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI:                           2.76
    File::Spec:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
